Np 44636 implementing storage
BIBSYSDEV/nva-orcid-client pull request #14
Opened 2023-05-02 07:42 UTC by anetteOlli

2023-05-02 12:25 UTC, truhacevkir approved these changes

2023-05-02 12:25 UTC, truhacevkir commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +    public void shouldThrowExceptionIfDynamoIsWorking() {
du mente sikkert IsNotWorking

2023-05-03 09:21 UTC, anetteOlli commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +    public void shouldThrowExceptionIfDynamoIsWorking() {
Fikset

2023-05-03 14:20 UTC, ketilaa approved these changes

2023-05-04 07:02 UTC, brinxmat requested changes

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/model/storage/OrcidCredentialsDao.java
> +        Item item = attempt(() -> Item.fromJSON(
Let's use `var` in the new files :)

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/OrcidServiceImpl.java
> +        TransactWriteItem transactionItem = transactionItemsForOrcidCredentialsInsertion(orcidCredentials);
`var`

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ReadOrcidCredentialsService.java
> +        AttributeValue partKeyValue = new AttributeValue(orcidCredentials.getOrcid().toString());
`var`

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ReadOrcidCredentialsService.java
> +        AttributeValue partKeyValue = new AttributeValue(orcidCredentials.getOrcid().toString());
In the entire file

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ReadOrcidCredentialsService.java
> +        return result;
Is there a reason to not return the Item since we call getItem directly after calling the method?

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/OrcidServiceImpl.java
> +                   .orElse(null);
Probably just return the optional and delegate the decision about what to do with this to the caller

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ServiceWithTransactions.java
> +        Put put = new Put()
`var`

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +    public void shouldBePossibleToStoreOrcidCredentials() {
Fix test visibility in file

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        URI orcid = UriWrapper.fromUri("").getUri();
`var`

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
```
        var orcidCredentials = randomOrcidCredentials();
        var actual = orcidService.createOrcidCredentials(orcidCredentials.copy());
        assertThat(actual.getModified(), doesNotHaveEmptyValues());
        assertThat(actual.getCreated(), is(equalTo(actual.getModified())));
        assertThat(actual.hasSameCredentials(orcidCredentials), is(true));
```

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
The hasSameCredentials seems a bit wacky, but we're not interested in modified and created when comparing credentials, I guess?

In OrcidCredentials:

```

    @Override
    @JacocoGenerated
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof OrcidCredentials)) {
            return false;
        }
        OrcidCredentials that = (OrcidCredentials) o;
        return hasSameCredentials(that)
               && Objects.equals(getModified(), that.getModified())
               && Objects.equals(getCreated(), that.getCreated());
    }

    @Override
    @JacocoGenerated
    public int hashCode() {
        return Objects.hash(getOrcid(), getAccessToken(), getTokenType(), getExpiresIn(), getTokenVersion(),
                            isPersistent(),
                            getIdToken(), getTokenId(), getModified(), getCreated());
    }

    public boolean hasSameCredentials(OrcidCredentials credentials) {
        return getExpiresIn() == credentials.getExpiresIn()
               && isPersistent() == credentials.isPersistent()
               && getTokenId() == credentials.getTokenId()
               && Objects.equals(getOrcid(), credentials.getOrcid())
               && Objects.equals(getAccessToken(), credentials.getAccessToken())
               && Objects.equals(getTokenType(), credentials.getTokenType())
               && Objects.equals(getTokenVersion(), credentials.getTokenVersion())
               && Objects.equals(getIdToken(), credentials.getIdToken());
    }
```

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
(I looked at Hamcrest for matchers that allow us to exclude fields in beans, but they have issues…)

2023-05-04 07:02 UTC, brinxmat commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
Also, the expectation is that that the modified and created dates are the same? Is there an update expectation too?

2023-05-05 08:00 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/OrcidServiceImpl.java
> +                   .orElse(null);
On second thought: I think I want to throw an exception. Having public Optional<orcidCredentials> createOrcidCredentials in orcidService will make it difficult to assert what went wrong.

2023-05-05 08:06 UTC, anetteOlli commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +    public void shouldBePossibleToStoreOrcidCredentials() {
You mean remove the "public" keyword? 
Done

2023-05-05 08:11 UTC, anetteOlli commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
For now there isn't an expectation for an update function. But I imagine there will be a need one day.

2023-05-05 08:12 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/model/storage/OrcidCredentialsDao.java
> +        Item item = attempt(() -> Item.fromJSON(
Fixed

2023-05-05 08:12 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/OrcidServiceImpl.java
> +        TransactWriteItem transactionItem = transactionItemsForOrcidCredentialsInsertion(orcidCredentials);
Fixed

2023-05-05 08:12 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ReadOrcidCredentialsService.java
> +        AttributeValue partKeyValue = new AttributeValue(orcidCredentials.getOrcid().toString());
Fixed

2023-05-05 08:12 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ReadOrcidCredentialsService.java
> +        return result;
The reason is brain lag.
Fixed

2023-05-05 08:13 UTC, anetteOlli commented on orcid-commons/src/main/java/no/sikt/nva/orcid/commons/service/ServiceWithTransactions.java
> +        Put put = new Put()
Fixed

2023-05-05 08:13 UTC, anetteOlli commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        URI orcid = UriWrapper.fromUri("").getUri();
Fixed

2023-05-05 08:13 UTC, anetteOlli commented on orcid-commons/src/test/java/no/sikt/nva/orcid/commons/service/OrcidServiceTest.java
> +        assertThat(persistedOrcidCredentials.getModified(), is(notNullValue()));
Implemented your suggestion

2023-05-08 13:33 UTC, brinxmat approved these changes

2023-05-08 13:34 UTC, merged