Np 44638 handler for storing credentials
BIBSYSDEV/nva-orcid-client pull request #18
Opened 2023-05-08 13:41 UTC by anetteOlli

2023-05-08 13:52 UTC, anetteOlli commented
Kjetil har poengtert svakheter her allerede i PR'en jeg har på frontenden:
Nå må frontenden gjøre dette i tre trinn:
1. snakke med orcid og sjekke at credentialsene er ekte.
2. Snakke med cristin og lagre orciden på personen
3. Så lagre credentialsene.

Det er altså 3 trinn som kan feile uten at brukeren kan gjøre noe som helst fornuftig med feilene.

Kan vi gjøre noe for å forbedre dette?

2023-05-08 14:03 UTC, brinxmat requested changes

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        if (!input.getOrcid().toString().contains(orcidFromCristin.get())) {
I'm going to be a pedant and ask that you write a test where NPE is checked in both input and retrieved cases (the retrieved case is probably covered already)

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        logger.info(input.getOrcid().toString());
Can you add a string that explains what is being logged?

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    }
Full-on O-man style:

```
    private URI craftUserUri(String userName) throws URISyntaxException {
        return new URIBuilder().setHost(apiHost)
                .setPath(constructPersonPath(userName))
                .setScheme(HTTPS_SCHEME)
                .build();
    }

    private static String constructPersonPath(String userName) {
        return CRISTIN_PERSON_PATH + extractUserIdentifierFromUserName(userName);
    }

    private static String extractUserIdentifierFromUserName(String userName) {
        return userName.split(USERNAME_DELIMITER)[0];
    }
```

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private Optional<String> getOrcidIdentifierFromResponsBody(String responseBody) throws JsonProcessingException {
Typo

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private Optional<String> getOrcidFromResponse(HttpResponse<String> response) throws JsonProcessingException {
`get` -> reserved for bean property getters, probably `extract`

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private Optional<String> getOrcidFromResponse(HttpResponse<String> response) throws JsonProcessingException {
Here and elsewhere

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +        return response;
Looks like a candidate for resilience Retry

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/test/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunctionTest.java
> +public class StoreOrcidCredentialsFunctionTest extends OrcidLocalTestDatabase {
visibility

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/test/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunctionTest.java
> +public class StoreOrcidCredentialsFunctionTest extends OrcidLocalTestDatabase {
Also for functions

2023-05-08 14:03 UTC, brinxmat commented on orcid-rest/src/test/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunctionTest.java
> +        assertThat(persistedOrcidCredentials, is(equalTo(orcidCredentials)));
persistedOrcidCredentials.hasSameCredentials

2023-05-08 14:31 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        if (!input.getOrcid().toString().contains(orcidFromCristin.get())) {
Going to argue with your here: I have setup api-gateway rules for this already. 

![image](https://user-images.githubusercontent.com/44363838/236851292-80b2d2c8-05aa-41fa-84a2-56c70828cb16.png)

Api-gateway already does the null check for me.

2023-05-08 14:40 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        if (!input.getOrcid().toString().contains(orcidFromCristin.get())) {
You get the same error if you try without orcid in the request body.

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        logger.info(input.getOrcid().toString());
fixed

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    }
fixed

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private Optional<String> getOrcidIdentifierFromResponsBody(String responseBody) throws JsonProcessingException {
fixed

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private Optional<String> getOrcidFromResponse(HttpResponse<String> response) throws JsonProcessingException {
fixed

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/test/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunctionTest.java
> +public class StoreOrcidCredentialsFunctionTest extends OrcidLocalTestDatabase {
fixed

2023-05-08 14:45 UTC, anetteOlli commented on orcid-rest/src/test/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunctionTest.java
> +        assertThat(persistedOrcidCredentials, is(equalTo(orcidCredentials)));
fixed

2023-05-08 15:26 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +        return response;
I agree.

2023-05-08 15:28 UTC, anetteOlli commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private String sendGetCristinPersonRequest(HttpRequest httpRequest) {
I think it's a bit weird mixing the vavr Try methods with the NVA attempts.

2023-05-09 06:31 UTC, brinxmat approved these changes

2023-05-09 06:31 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/StoreOrcidCredentialsFunction.java
> +        if (!input.getOrcid().toString().contains(orcidFromCristin.get())) {
I guess the operative word in what I wrote was _pedant_ :D

2023-05-09 06:31 UTC, brinxmat commented on orcid-rest/src/main/java/no/sikt/nva/orcid/handlers/UserOrcidResolver.java
> +    private String sendGetCristinPersonRequest(HttpRequest httpRequest) {
It is, we should remove attempt, I guess.

2023-05-09 08:42 UTC, truhacevkir approved these changes

2023-05-09 12:43 UTC, merged